name: cmot-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - networkx
    - opencv-python
    - tqdm
    - numpy<2
    - scipy
    - polars
    - stardist
    - tensorflow-cpu
    - black[jupyter]==24.10.0
    - isort==5.13.2
    - git+https://github.com/lettlini/overlap-tracking
    - git+https://github.com/lettlini/core-data-utils
    - pre-commit
